# **********************************************************************
#
# Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
#
# This copy of Ice is licensed to you under the terms described in the
# ICE_LICENSE file included in this distribution.
#
# **********************************************************************
#
# Ice version 3.5.1
#
# <auto-generated>
#
# Generated from file `SHcontrol.ice'
#
# Warning: do not edit this file.
#
# </auto-generated>
#

import Ice, IcePy

# Start of module SHControl
_M_SHControl = Ice.openModule('SHControl')
__name__ = 'SHControl'

if 'SignalHound' not in _M_SHControl.__dict__:
    _M_SHControl.SignalHound = Ice.createTempClass()
    class SignalHound(Ice.Object):
        def __init__(self):
            if Ice.getType(self) == _M_SHControl.SignalHound:
                raise RuntimeError('SHControl.SignalHound is an abstract class')

        def ice_ids(self, current=None):
            return ('::Ice::Object', '::SHControl::SignalHound')

        def ice_id(self, current=None):
            return '::SHControl::SignalHound'

        def ice_staticId():
            return '::SHControl::SignalHound'
        ice_staticId = staticmethod(ice_staticId)

        def message(self, s, current=None):
            pass

        def __str__(self):
            return IcePy.stringify(self, _M_SHControl._t_SignalHound)

        __repr__ = __str__

    _M_SHControl.SignalHoundPrx = Ice.createTempClass()
    class SignalHoundPrx(Ice.ObjectPrx):

        def message(self, s, _ctx=None):
            return _M_SHControl.SignalHound._op_message.invoke(self, ((s, ), _ctx))

        def begin_message(self, s, _response=None, _ex=None, _sent=None, _ctx=None):
            return _M_SHControl.SignalHound._op_message.begin(self, ((s, ), _response, _ex, _sent, _ctx))

        def end_message(self, _r):
            return _M_SHControl.SignalHound._op_message.end(self, _r)

        def checkedCast(proxy, facetOrCtx=None, _ctx=None):
            return _M_SHControl.SignalHoundPrx.ice_checkedCast(proxy, '::SHControl::SignalHound', facetOrCtx, _ctx)
        checkedCast = staticmethod(checkedCast)

        def uncheckedCast(proxy, facet=None):
            return _M_SHControl.SignalHoundPrx.ice_uncheckedCast(proxy, facet)
        uncheckedCast = staticmethod(uncheckedCast)

    _M_SHControl._t_SignalHoundPrx = IcePy.defineProxy('::SHControl::SignalHound', SignalHoundPrx)

    _M_SHControl._t_SignalHound = IcePy.defineClass('::SHControl::SignalHound', SignalHound, -1, (), True, False, None, (), ())
    SignalHound._ice_type = _M_SHControl._t_SignalHound

    SignalHound._op_message = IcePy.Operation('message', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0),), (((), IcePy._t_string, False, 0),), None, ())

    _M_SHControl.SignalHound = SignalHound
    del SignalHound

    _M_SHControl.SignalHoundPrx = SignalHoundPrx
    del SignalHoundPrx

# End of module SHControl
